---
title: "TWFE"
author: "Kyohei Sato"
date: "2024-11-14"
output: html_document
---

```{r setup, include=FALSE}
# Install packages

if (!require(pacman)) install.packages("pacman")
pacman::p_load(
  cem, cobalt, fixest, gtExtras, here,
  labelled, RColorBrewer, rlist, scales, tidyverse, estimatr, modelsummary,
  fastDummies, did, DT, lfe
)
pacman::p_load_gh("rstudio/gt")

# Read and clean data

df_basic <- 
  read_csv(here::here("/masters_thesis/data/panel/dat_basic.csv")) |> 
  filter(wage_per_hour > 700, wage_per_hour < 10000)

df_cov <-
  read_csv(here::here("/masters_thesis/data/panel/dat_panel_cov.csv"))

# 1. まず、元データの確認
# print("元のd_term_fixedの分布:")
# table(df_cov$d_term_fixed, useNA = "ifany")

# Prepare data for analysis
df_full <- df_basic |> 
  left_join(df_cov, by = c("ID", "year"))|> 
  mutate(age_10s = age %/% 10,
         d_position = if_else(position <= 7, 1, 0),
         small_firm = if_else(firm_size <= 7, 1, 0),
         d_term_fixed = if_else(d_term_fixed == 1, 1, 0), #期間が定められていれば１
         d_contract_change = if_else(d_reg_nonreg == 1 | q_nonreg_reg == 1,
                                     1, 0),
         relativetime = year - year_entry_current - 5
         )

# -5年の時点で契約雇用期間のあるIDを特定
df_full <- df_full |>
   group_by(ID) |>
   filter(any(relativetime == -5 & d_term_fixed == 1))

# df_check <- df_full_corrected |>
#   filter(relativetime == -5)
# table(df_check$d_term_fixed)

df_full <- df_full|>
  mutate(
    treat = if_else(year_entry_current >= 2013 & year_entry_current <= 2017, 1, 0),
    post_treat = case_when(
      year_entry_current == 2013 & year >= 2018 ~ 1,
      year_entry_current == 2014 & year >= 2019 ~ 1,
      year_entry_current == 2015 & year >= 2020 ~ 1,
      year_entry_current == 2016 & year >= 2021 ~ 1,
      year_entry_current == 2017 & year >= 2022 ~ 1,
      TRUE ~ 0)) |> 
  mutate(eventtime = if_else(treat == 1, relativetime, 0))


# 最初に介入を受ける年を特定
df_full <- 
df_full |> 
  group_by(ID) |> 
  mutate(first.treat = first(year[post_treat == 1], na_rm = T)) |> 
  mutate(first.treat = replace_na(first.treat, 0),
         d_term_fixed = 1- d_term_fixed) |>
  ungroup()

```

## Sample Size
```{r, echo=FALSE}
sample_sizes <- df_full %>%
  distinct(ID, first.treat) %>%
  group_by(first.treat) %>%
  summarise(n = n()) %>%
  arrange(first.treat)

datatable(sample_sizes)

```

```{r, echo=FALSE}
## Setting

df_twfe <- df_full %>%
  mutate(
    time_til = year - first.treat,
    lead1 = case_when(time_til == -1 ~ 1, TRUE ~ 0),
    lead2 = case_when(time_til == -2 ~ 1, TRUE ~ 0),
    lead3 = case_when(time_til == -3 ~ 1, TRUE ~ 0),
    lead4 = case_when(time_til == -4 ~ 1, TRUE ~ 0),
    lead5 = case_when(time_til == -5 ~ 1, TRUE ~ 0),
    lead6 = case_when(time_til == -6 ~ 1, TRUE ~ 0),
    lead7 = case_when(time_til == -7 ~ 1, TRUE ~ 0),
    
    lag0 = case_when(time_til == 0 ~ 1, TRUE ~ 0),
    lag1 = case_when(time_til == 1 ~ 1, TRUE ~ 0),
    lag2 = case_when(time_til == 2 ~ 1, TRUE ~ 0),
    lag3 = case_when(time_til == 3 ~ 1, TRUE ~ 0),
    lag4 = case_when(time_til == 4 ~ 1, TRUE ~ 0),
    lag5 = case_when(time_til == 5 ~ 1, TRUE ~ 0)
  )

event_study_formula <- as.formula(
  paste("d_term_fixed ~ + ",
        paste(
          paste(paste("lead", 1:7, sep = ""), collapse = " + "),
          paste(paste("lag", 1:5, sep = ""), collapse = " + "), sep = " + "),
        "| year + ID | 0 | ID"
  ),
)

event_study_reg <- felm(event_study_formula, data = df_twfe)
summary(event_study_reg)

```


## Event Study { .tabset}
$$
\begin{aligned}
Y_{it} = \alpha_i + \lambda_t + \sum_{r \neq -1} \beta_r \mathbb{I} (t =  r) + \epsilon_{it}
\end{aligned}
$$

### Indefinite-Term Contract
```{r, echo=FALSE, message=FALSE}
# order of the coefficients for the plot
plot_order <- c("lead7", 
                "lead6", "lead5", "lead4", "lead3", 
                "lead2", "lead1", "lag1", 
                "lag2", "lag3", "lag4", "lag5")

# grab the clustered standard errors
# and average coefficient estimates
# from the regression, label them accordingly
# add a zero'th lag for plotting purposes
leadslags_plot <- tibble(
  sd = c(event_study_reg$cse[plot_order], 0),
  mean = c(coef(event_study_reg)[plot_order], 0),
  label = c(-7,-6, -5, -4, -3, -2, -1, 1,2,3,4,5, 0)
)

# This version has a point-range at each
# estimated lead or lag
# comes down to stylistic preference at the
# end of the day!
leadslags_plot %>%
  ggplot(aes(x = label, y = mean,
             ymin = mean-1.96*sd, 
             ymax = mean+1.96*sd)) +
  geom_pointrange() +
  theme_minimal() +
  xlab("Years before and after castle doctrine expansion") +
  ylab("log(Homicide Rate)") +
  geom_hline(yintercept = 0,
             linetype = "dashed") +
  geom_vline(xintercept = 0,
             linetype = "dashed")
  

# This version includes
# an interval that traces the confidence intervals
# of your coefficients
leadslags_plot %>%
  ggplot(aes(x = label, y = mean,
             ymin = mean-1.96*sd, 
             ymax = mean+1.96*sd)) +
  # this creates a red horizontal line
  geom_line() + 
  geom_point() +
  geom_ribbon(alpha = 0.2) +
  theme_minimal() +
  # Important to have informative axes labels!
  xlab("Years before and after castle doctrine expansion") +
  ylab("log(Homicide Rate)") +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0)
```

### Wage
```{r, echo=FALSE, message=FALSE}

event_study_formula2 <- as.formula(
  paste("logwage ~ + ",
        paste(
          paste(paste("lead", 1:7, sep = ""), collapse = " + "),
          paste(paste("lag", 1:5, sep = ""), collapse = " + "), sep = " + "),
        "| year + ID| 0 | ID"
  ),
)

event_study_reg2 <- felm(event_study_formula2, data = df_twfe)
summary(event_study_reg2)

```


```{r}
leadslags_plot2 <- tibble(
  sd = c(event_study_reg2$cse[plot_order], 0),
  mean = c(coef(event_study_reg2)[plot_order], 0),
  label = c(-7,-6, -5, -4, -3, -2, -1, 1,2,3,4,5, 0)
)

# This version has a point-range at each
# estimated lead or lag
# comes down to stylistic preference at the
# end of the day!
leadslags_plot2 %>%
  ggplot(aes(x = label, y = mean,
             ymin = mean-1.96*sd, 
             ymax = mean+1.96*sd)) +
  geom_pointrange() +
  theme_minimal() +
  xlab("Years before and after castle doctrine expansion") +
  ylab("log(Homicide Rate)") +
  geom_hline(yintercept = 0,
             linetype = "dashed") +
  geom_vline(xintercept = 0,
             linetype = "dashed")
  

# This version includes
# an interval that traces the confidence intervals
# of your coefficients
leadslags_plot2 %>%
  ggplot(aes(x = label, y = mean,
             ymin = mean-1.96*sd, 
             ymax = mean+1.96*sd)) +
  # this creates a red horizontal line
  geom_line() + 
  geom_point() +
  geom_ribbon(alpha = 0.2) +
  theme_minimal() +
  # Important to have informative axes labels!
  xlab("Years before and after castle doctrine expansion") +
  ylab("log(Homicide Rate)") +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0)

```

